elements:
- id: test_opis
  label: Test opis
  yolo_class: element
  created_at: '2026-06-14T09:37:42.195184+00:00'
- id: rozłącznik
  label: rozłącznik
  yolo_class: element
  created_at: '2026-06-15T17:35:05.185713+00:00'
- id: rozłącznik_bezpiecznikowy
  label: Rozłącznik bezpiecznikowy
  yolo_class: element
  created_at: '2026-06-15T17:35:05.185713+00:00'
- id: oznaczenie_kabla
  label: Oznaczenie kabla
  yolo_class: element
  created_at: '2026-06-15T17:35:05.185713+00:00'
- id: oznaczenie_przewodu
  label: Oznaczenie przewodu
  yolo_class: element
  created_at: '2026-06-15T17:35:05.185713+00:00'
- id: znak_uziemienia
  label: Znak uziemienia
  yolo_class: element
  created_at: '2026-06-15T17:35:05.185713+00:00'
- id: zwarta_listwa_złączek
  label: Zwarta listwa złączek
  yolo_class: element
  created_at: '2026-06-15T17:35:05.185713+00:00'
- id: złączka
  label: złączka
  yolo_class: element
  created_at: '2026-06-15T17:35:05.185713+00:00'
- id: listwa_złączek
  label: Listwa złączek
  yolo_class: element
  created_at: '2026-06-15T17:35:05.185713+00:00'
- id: symbol_napięcia
  label: Symbol napięcia
  yolo_class: element
  created_at: '2026-06-15T17:35:05.185713+00:00'
- id: czujnik_fotoelektryczny
  label: czujnik fotoelektryczny
  yolo_class: element
  created_at: '2026-06-15T17:39:16.284959+00:00'
- id: strzałka_potencjału
  label: Strzałka potencjału
  yolo_class: element
  created_at: '2026-06-15T17:39:25.108694+00:00'
- id: mostek
  label: mostek
  yolo_class: element
  created_at: '2026-06-15T17:42:37.079535+00:00'
- id: strzałka_potencjału_wejściowa
  label: Strzałka potencjału (wejściowa)
  yolo_class: element
  created_at: '2026-06-15T17:43:16.443500+00:00'
- id: strzałka_potencjału_wyjściowa
  label: Strzałka potencjału (wyjściowa)
  yolo_class: element
  created_at: '2026-06-15T17:43:24.385142+00:00'
- id: styki_przekaźnika
  label: styki przekaźnika
  yolo_class: element
  created_at: '2026-06-15T17:44:05.985206+00:00'
- id: ogranicznik_przepięć
  label: ogranicznik przepięć
  yolo_class: element
  created_at: '2026-06-15T17:44:20.471836+00:00'
- id: terminal_plc
  label: terminal PLC
  yolo_class: element
  created_at: '2026-06-15T17:46:58.678009+00:00'
- id: terminal_przyłączeniowy
  label: terminal przyłączeniowy
  yolo_class: element
  created_at: '2026-06-15T17:52:41.567939+00:00'
- id: terminale_urządzenia
  label: terminale urządzenia
  yolo_class: element
  created_at: '2026-06-15T17:52:55.398294+00:00'
- id: wyłącznik_kombinowany
  label: Wyłącznik kombinowany
  yolo_class: element
  created_at: '2026-06-15T17:54:35.476366+00:00'
- id: gniazdo
  label: gniazdo
  yolo_class: element
  created_at: '2026-06-15T17:54:52.406665+00:00'
