elements:
- id: test_opis
  label: Test opis
  yolo_class: element
  created_at: '2026-06-14T09:37:42.195184+00:00'
- id: rozłącznik
  label: rozłącznik
  yolo_class: element
  created_at: '2026-06-15T17:35:05.185713+00:00'
- id: rozłącznik_bezpiecznikowy
  label: Rozłącznik bezpiecznikowy
  yolo_class: element
  created_at: '2026-06-15T17:35:05.185713+00:00'
- id: oznaczenie_kabla
  label: Oznaczenie kabla
  yolo_class: element
  created_at: '2026-06-15T17:35:05.185713+00:00'
- id: oznaczenie_przewodu
  label: Oznaczenie przewodu
  yolo_class: element
  created_at: '2026-06-15T17:35:05.185713+00:00'
- id: znak_uziemienia
  label: Znak uziemienia
  yolo_class: element
  created_at: '2026-06-15T17:35:05.185713+00:00'
- id: zwarta_listwa_złączek
  label: Zwarta listwa złączek
  yolo_class: element
  created_at: '2026-06-15T17:35:05.185713+00:00'
- id: złączka
  label: złączka
  yolo_class: element
  created_at: '2026-06-15T17:35:05.185713+00:00'
- id: listwa_złączek
  label: Listwa złączek
  yolo_class: element
  created_at: '2026-06-15T17:35:05.185713+00:00'
- id: symbol_napięcia
  label: Symbol napięcia
  yolo_class: element
  created_at: '2026-06-15T17:35:05.185713+00:00'
- id: czujnik_fotoelektryczny
  label: czujnik fotoelektryczny
  yolo_class: element
  created_at: '2026-06-15T17:39:16.284959+00:00'
- id: strzałka_potencjału
  label: Strzałka potencjału
  yolo_class: element
  created_at: '2026-06-15T17:39:25.108694+00:00'
- id: mostek
  label: mostek
  yolo_class: element
  created_at: '2026-06-15T17:42:37.079535+00:00'
- id: strzałka_potencjału_wejściowa
  label: Strzałka potencjału (wejściowa)
  yolo_class: element
  created_at: '2026-06-15T17:43:16.443500+00:00'
- id: strzałka_potencjału_wyjściowa
  label: Strzałka potencjału (wyjściowa)
  yolo_class: element
  created_at: '2026-06-15T17:43:24.385142+00:00'
- id: styki_przekaźnika
  label: styki przekaźnika
  yolo_class: element
  created_at: '2026-06-15T17:44:05.985206+00:00'
- id: ogranicznik_przepięć
  label: ogranicznik przepięć
  yolo_class: element
  created_at: '2026-06-15T17:44:20.471836+00:00'
- id: terminal_plc
  label: terminal PLC
  yolo_class: element
  created_at: '2026-06-15T17:46:58.678009+00:00'
- id: terminal_przyłączeniowy
  label: terminal przyłączeniowy
  yolo_class: element
  created_at: '2026-06-15T17:52:41.567939+00:00'
- id: terminale_urządzenia
  label: terminale urządzenia
  yolo_class: element
  created_at: '2026-06-15T17:52:55.398294+00:00'
- id: wyłącznik_kombinowany
  label: Wyłącznik kombinowany
  yolo_class: element
  created_at: '2026-06-15T17:54:35.476366+00:00'
- id: gniazdo
  label: gniazdo
  yolo_class: element
  created_at: '2026-06-15T17:54:52.406665+00:00'
- id: lampka
  label: lampka
  yolo_class: element
  created_at: '2026-06-15T17:55:31.550126+00:00'
- id: styki
  label: styki
  yolo_class: element
  created_at: '2026-06-15T17:56:18.105095+00:00'
- id: ter
  label: ter
  yolo_class: element
  created_at: '2026-06-15T17:56:26.653080+00:00'
- id: styk_krańcówki
  label: styk krańcówki
  yolo_class: element
  created_at: '2026-06-15T17:57:06.758270+00:00'
- id: wyłącznik_nadprądowy
  label: wyłącznik nadprądowy
  yolo_class: element
  created_at: '2026-06-15T17:58:15.142957+00:00'
- id: przetwornik_prąd_przemiennystały
  label: przetwornik - prąd przemienny/stały
  yolo_class: element
  created_at: '2026-06-15T17:58:50.455920+00:00'
- id: połączenie_przewodów
  label: połączenie przewodów
  yolo_class: element
  created_at: '2026-06-15T17:59:32.360530+00:00'
- id: zasilacz
  label: zasilacz
  yolo_class: element
  created_at: '2026-06-15T18:00:11.976038+00:00'
- id: dioda
  label: dioda
  yolo_class: element
  created_at: '2026-06-15T18:02:42.182724+00:00'
- id: mos
  label: mos
  yolo_class: element
  created_at: '2026-06-15T18:02:58.496497+00:00'
- id: gniazdo_rj_45
  label: gniazdo RJ-45
  yolo_class: element
  created_at: '2026-06-15T18:13:41.065530+00:00'
- id: gniazdo_światłowodu
  label: gniazdo światłowodu
  yolo_class: element
  created_at: '2026-06-15T18:14:36.651276+00:00'
- id: krańcówka
  label: krańcówka
  yolo_class: element
  created_at: '2026-06-15T18:15:05.217254+00:00'
- id: moduł_redundantny
  label: moduł redundantny
  yolo_class: element
  created_at: '2026-06-15T18:15:19.075443+00:00'
- id: switch
  label: switch
  yolo_class: element
  created_at: '2026-06-15T18:17:20.152048+00:00'
- id: przetwornik_temperaturaprąd
  label: przetwornik - temperatura/prąd
  yolo_class: element
  created_at: '2026-06-15T18:22:40.703815+00:00'
- id: ekranowanie_przewodu
  label: ekranowanie przewodu
  yolo_class: element
  created_at: '2026-06-15T18:23:29.194879+00:00'
- id: ekranowanie_kabla
  label: ekranowanie kabla
  yolo_class: element
  created_at: '2026-06-15T18:23:37.188088+00:00'
- id: listwa_zaciskowa
  label: listwa zaciskowa
  yolo_class: element
  created_at: '2026-06-15T18:24:22.359195+00:00'
- id: przekaźnik_polaryzowany
  label: przekaźnik polaryzowany
  yolo_class: element
  created_at: '2026-06-15T18:27:35.181772+00:00'
- id: przycisk
  label: przycisk
  yolo_class: element
  created_at: '2026-06-15T18:30:58.779007+00:00'
- id: lampka_wewnętrzna
  label: lampka wewnętrzna
  yolo_class: element
  created_at: '2026-06-15T18:36:58.270361+00:00'
- id: czujnik_optyczny
  label: czujnik optyczny
  yolo_class: element
  created_at: '2026-06-15T18:37:30.316810+00:00'
- id: symbol_ex
  label: symbol EX
  yolo_class: element
  created_at: '2026-06-15T18:41:11.249224+00:00'
- id: symbol_brak_ex
  label: symbol brak EX
  yolo_class: element
  created_at: '2026-06-15T18:41:19.482314+00:00'
- id: separator_dwukanałowy
  label: separator dwukanałowy
  yolo_class: element
  created_at: '2026-06-15T18:42:10.764927+00:00'
- id: separator
  label: separator
  yolo_class: element
  created_at: '2026-06-15T18:42:25.706317+00:00'
- id: urządzenie
  label: urządzenie
  yolo_class: element
  created_at: '2026-06-15T18:46:25.946168+00:00'
- id: terminal_sterownika_safety
  label: terminal sterownika safety
  yolo_class: element
  created_at: '2026-06-15T18:55:11.284818+00:00'
