# AUTO-GENEROWANE przez train/dataset_export.py (z pola `tag` adnotacji).
# Nie edytuj recznie — zostanie nadpisane przy kolejnym eksporcie.
classes:
- emergency_stop
- zlaczka
- mostek
- strzalka_potencjalu_wejsciowa
- strzalka_potencjalu_wyjsciowa
- 0vdc_1v2_27_7
- 0vdc_2v2_27_7
- 0vdc_as0
- 0vdc_as1
- 0vdc_saf
- 0vdc_saf_28_7
- '1'
- '10'
- '11'
- '12'
- '13'
- '14'
- '15'
- '16'
- '17'
- '18'
- '19'
- '2'
- '20'
- '21'
- '22'
- '23'
- '24'
- 24vdc_1v2_27_7
- 24vdc_2v2_27_7
- 24vdc_as0
- 24vdc_as1
- 24vdc_di_28_3
- 24vdc_kbd
- 24vdc_saf
- 24vdc_saf_28_3
- '25'
- '26'
- '27'
- '28'
- '29'
- '3'
- '30'
- '31'
- '32'
- '33'
- '34'
- '35'
- '36'
- '4'
- '5'
- '6'
- '7'
- '8'
- '9'
- as0
- as1
- bd1_aux
- bd1_e
- bd1_ossd1
- bd1_ossd2
- bd1_r
- bd2_3
- bd2_aux
- bd2_ossd1
- bd2_ossd2
- bd2_r
- bk
- bn
- bu
- fs24_1
- fs24_2
- gy
- kbd1_1
- kbd_2_1
- ks_24vdc_1
- ks_24vdc_2
- lds_2_45
- mutea
- muteb
- pe
- pk
- rd
- s0vdc_a20
- s0vdc_bk1
- s0vdc_bk2
- s0vdc_valve
- s24vdc_a20
- s24vdc_kb
- s24vdc_ks10
- s24vdc_ks11
- s24vdc_ok_1
- s24vdc_ok_2
- s24vdc_valve
- saf1
- saf1_ossd1
- saf1_ossd2
- saf1_plc_64_1
- saf2
- saf2_plc_64_2
- saf3
- saf3_plc_64_3
- saf4_1
- saf4_2
- saf4_3
- saf4_4
- saf4_5
- saf4_6
- saf4_plc_64_4
- saf5_plc_64_5
- saf6_plc_64_6
- skbd1
- skbd2
- styki_przekaznika
- test_sig_t1
- test_sig_t2
- urzadzenie
- wh
- ye
